src/Entity/ExpenseTransaction.php
<?php

namespace App\Entity;

use App\Repository\ExpenseTransactionRepository;
use DateTimeImmutable;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ExpenseTransactionRepository::class)]
class ExpenseTransaction
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'expenseTransactions')]
    #[ORM\JoinColumn(nullable: false)]
    private ?ExpenseCategory $expenseCategory = null;

    #[ORM\ManyToOne(inversedBy: 'expenseTransactions')]
    #[ORM\JoinColumn(nullable: false)]
    private ?ExpensePaymentCategory $expensePaymentCategory = null;

    #[ORM\ManyToOne(inversedBy: 'expenseTransactions')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $payment_date = null;

    #[ORM\Column]
    private ?int $amount = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $note = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $updated_at = null;

    public function __construct()
    {
        $this->created_at = new DateTimeImmutable();
        $this->updated_at = new DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getExpenseCategory(): ?ExpenseCategory
    {
        return $this->expenseCategory;
    }

    public function setExpenseCategory(?ExpenseCategory $expenseCategory): static
    {
        $this->expenseCategory = $expenseCategory;

        return $this;
    }

    public function getExpensePaymentCategory(): ?ExpensePaymentCategory
    {
        return $this->expensePaymentCategory;
    }

    public function setExpensePaymentCategory(?ExpensePaymentCategory $expensePaymentCategory): static
    {
        $this->expensePaymentCategory = $expensePaymentCategory;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function getPaymentDate(): ?\DateTimeImmutable
    {
        return $this->payment_date;
    }

    public function setPaymentDate(\DateTimeImmutable $payment_date): static
    {
        $this->payment_date = $payment_date;

        return $this;
    }

    public function getAmount(): ?int
    {
        return $this->amount;
    }

    public function setAmount(int $amount): static
    {
        $this->amount = $amount;

        return $this;
    }

    public function getNote(): ?string
    {
        return $this->note;
    }

    public function setNote(string $note): static
    {
        $this->note = $note;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeImmutable $updated_at): static
    {
        $this->updated_at = $updated_at;

        return $this;
    }
}

src/Entity/UserAccount.php
<?php

namespace App\Entity;

use App\Repository\UserAccountRepository;
use DateTimeImmutable;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: UserAccountRepository::class)]
class UserAccount
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\OneToOne(inversedBy: 'userAccount', cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\Column(length: 255)]
    private ?string $first_name = null;

    #[ORM\Column(length: 255)]
    private ?string $last_name = null;

    #[ORM\Column(length: 255)]
    private ?string $first_name_kana = null;

    #[ORM\Column(length: 255)]
    private ?string $last_name_kana = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $birth_date = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $updated_at = null;

    public function __construct()
    {
        $this->created_at = new DateTimeImmutable();
        $this->updated_at = new DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(User $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): static
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): static
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getFirstNameKana(): ?string
    {
        return $this->first_name_kana;
    }

    public function setFirstNameKana(string $first_name_kana): static
    {
        $this->first_name_kana = $first_name_kana;

        return $this;
    }

    public function getLastNameKana(): ?string
    {
        return $this->last_name_kana;
    }

    public function setLastNameKana(string $last_name_kana): static
    {
        $this->last_name_kana = $last_name_kana;

        return $this;
    }

    public function getBirthDate(): ?\DateTimeInterface
    {
        return $this->birth_date;
    }

    public function setBirthDate(\DateTimeInterface $birth_date): static
    {
        $this->birth_date = $birth_date;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeImmutable $updated_at): static
    {
        $this->updated_at = $updated_at;

        return $this;
    }
}

src/Controller/ExpenseTransactionController.php
<?php

namespace App\Controller;

use App\Entity\ExpenseTransaction;
use App\Form\ExpenseTransactionCreateType;
use App\Form\ExpenseTransactionEditType;
use App\Form\ExpenseTransactionIndexSearchType;
use App\Service\ExpenseTransactionService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

class ExpenseTransactionController extends AbstractController
{
    private $expenseTransactionService;

    public function __construct(ExpenseTransactionService $expenseTransactionService)
    {
        $this->expenseTransactionService = $expenseTransactionService;
    }

    public function index(Request $request): Response
    {
        $deviceType = $request->attributes->get('device');
        $routeName = $request->attributes->get('routeName');
        $headerInfo = $this->expenseTransactionService->getHeaderInfo($routeName, null);
        $footerInfo = $this->expenseTransactionService->getFooterInfo($routeName, null);

        $searchForm = $this->createForm(ExpenseTransactionIndexSearchType::class);
        $searchForm->handleRequest($request);

        $expenseTransactions = $this->expenseTransactionService->searchExpenseTransaction($searchForm);
        $aggregateExpensesByCategory = $this->expenseTransactionService->aggregateExpensesByCategory($expenseTransactions);

        $resultParameter = [
            'pageTitle' => $headerInfo['pageTitle'],
            'headerLinks' => $headerInfo['headerLinks'],
            'footerLinks' => $footerInfo['footerLinks'],
            'expenseTransactions' => $expenseTransactions,
            'aggregateExpensesByCategory' => $aggregateExpensesByCategory,
            'searchForm' => $searchForm->createView(),
        ];

        return $this->render("{$deviceType}/expense_transaction/index.html.twig", $resultParameter);
    }

    public function create(Request $request): Response
    {
        $deviceType = $request->attributes->get('device');

        $expenseTransaction = new ExpenseTransaction;
        $createForm = $this->createForm(ExpenseTransactionCreateType::class, $expenseTransaction);
        $createForm->handleRequest($request);

        if ($createForm->isSubmitted() && $createForm->isValid()) {
            $this->expenseTransactionService->registerExpenseTransaction($expenseTransaction, $this->getUser());

            return $this->redirectToRoute('expense_transaction_index');
        }

        return $this->render("{$deviceType}/expense_transaction/create.html.twig", [
            'createForm' => $createForm->createView(),
        ]);
    }

    public function edit($id, Request $request)
    {
        $deviceType = $request->attributes->get('device');

        $expenseTransaction = $this->expenseTransactionService->getExpenseTransaction($id);

        $editForm = $this->createForm(ExpenseTransactionEditType::class, $expenseTransaction);
        $editForm->handleRequest($request);

        if ($editForm->isSubmitted() && $editForm->isValid()) {
            $this->expenseTransactionService->updateExpenseTransaction($editForm);

            return $this->redirectToRoute('expense_transaction_index');
        }

        return $this->render("{$deviceType}/expense_transaction/edit.html.twig", [
            'editForm' => $editForm->createView(),
        ]);
    }

    public function delete($id)
    {
        $expenseTransaction = $this->expenseTransactionService->getExpenseTransaction($id);

        if ($expenseTransaction) {
            $this->expenseTransactionService->deleteExpenseTransaction($expenseTransaction);
        }

        return $this->redirectToRoute('expense_transaction_index');
    }
}

templates/mobile/expense_transaction/create.html.twig
{% extends 'mobile/_base_layout/base.html.twig' %}

{% block importmap %}
    {{ importmap(['mobile-base-layout', 'mobile-expense-transaction-create']) }}
{% endblock %}

{% block title %}支出新規登録{% endblock %}

{% block body %}
    <main>
        <div>
            <h1>支出新規登録</h1>
        </div>

        <div>
            {{ form_start(createForm) }}
                <div>
                    {{ form_label(createForm.payment_date) }}
                    {{ form_widget(createForm.payment_date) }}
                    {{ form_errors(createForm.payment_date) }}
                </div>
                <div>
                    {{ form_label(createForm.amount) }}
                    {{ form_widget(createForm.amount) }}
                    {{ form_errors(createForm.amount) }}
                </div>
                <div>
                    {{ form_label(createForm.note) }}
                    {{ form_widget(createForm.note) }}
                    {{ form_errors(createForm.note) }}
                </div>
                <div>
                    {{ form_label(createForm.expenseCategory) }}
                    {{ form_widget(createForm.expenseCategory) }}
                    {{ form_errors(createForm.expenseCategory) }}
                </div>
                <div>
                    {{ form_label(createForm.expensePaymentCategory) }}
                    {{ form_widget(createForm.expensePaymentCategory) }}
                    {{ form_errors(createForm.expensePaymentCategory) }}
                </div>
            {{ form_end(createForm) }}
        </div>

        <div>
            <a href="{{ path('expense_transaction_index') }}">キャンセル</a>
        </div>
    </main>
{% endblock %}

templates/mobile/expense_transaction/edit.html.twig
{% extends 'mobile/_base_layout/base.html.twig' %}

{% block importmap %}
    {{ importmap(['mobile-base-layout', 'mobile-expense-transaction-edit']) }}
{% endblock %}

{% block title %}支出詳細編集{% endblock %}

{% block body %}
    <main>
        <div>
            <h1>支出詳細編集</h1>
        </div>

        <div>
            {{ form_start(editForm) }}
                <div>
                    {{ form_label(editForm.payment_date) }}
                    {{ form_widget(editForm.payment_date) }}
                    {{ form_errors(editForm.payment_date) }}
                </div>
                <div>
                    {{ form_label(editForm.amount) }}
                    {{ form_widget(editForm.amount) }}
                    {{ form_errors(editForm.amount) }}
                </div>
                <div>
                    {{ form_label(editForm.note) }}
                    {{ form_widget(editForm.note) }}
                    {{ form_errors(editForm.note) }}
                </div>
                <div>
                    {{ form_label(editForm.expenseCategory) }}
                    {{ form_widget(editForm.expenseCategory) }}
                    {{ form_errors(editForm.expenseCategory) }}
                </div>
                <div>
                    {{ form_label(editForm.expensePaymentCategory) }}
                    {{ form_widget(editForm.expensePaymentCategory) }}
                    {{ form_errors(editForm.expensePaymentCategory) }}
                </div>
            {{ form_end(editForm) }}
        </div>

        <div>
            <a href="{{ path('expense_transaction_index') }}">キャンセル</a>
        </div>
    </main>
{% endblock %}

templates/mobile/expense_transaction/index.html.twig
{% extends 'mobile/_base_layout/base.html.twig' %}

{% block importmap %}
    {{ importmap(['mobile-base-layout', 'mobile-expense-transaction-index']) }}
{% endblock %}

{% block title %}支出一覧{% endblock %}

{% block body %}

    {% include 'mobile/_base_layout/base_header.html.twig' with {'pageTitle': pageTitle, 'headerLinks': headerLinks} %}

    <main>
        <details>
            <summary>検索フォーム</summary>
            <div id="searchContent" class="search-content">
                {{ form_start(searchForm) }}
                {{ form_widget(searchForm) }}
                {{ form_end(searchForm) }}
            </div>
        </details>

        <div class="table-total-price-content">
            <table class="table-total-price">
                <thead>
                    <tr>
                        <th>費目</th>
                        <th>設定額</th>
                        <th>使用額</th>
                        <th>差額</th>
                    </tr>
                </thead>
                <tbody>
                    {% set resultTotalePrices = aggregateExpensesByCategory['resultTotalePrices'] %}
                    {% set resultBudgetAmounts = aggregateExpensesByCategory['resultBudgetAmounts'] %}
                    {% for expenseCategoryName, resultTotalePrice in resultTotalePrices %}
                        <tr>
                            <td>{{ expenseCategoryName }}</td>
                            <td>{{ resultBudgetAmounts[expenseCategoryName] }}</td>
                            <td class="td-row-amount">{{ resultTotalePrice }}</td>
                            <td class="td-row-amount">{{ resultBudgetAmounts[expenseCategoryName] - resultTotalePrice }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

        <div class="table-expense-transactions-content">
            <table class="table-expense-transactions">
                <thead>
                    <tr>
                        {# <th>ID</th> #}
                        <th>決済日</th>
                        {# <th>決済者</th> #}
                        <th>費目</th>
                        {# <th>決済種別</th> #}
                        <th>金額</th>
                        {# <th>メモ</th> #}
                        <th>操作</th>
                    </tr>
                </thead>
                <tbody>
                    {% for expenseTransaction in expenseTransactions %}
                        <tr>
                            {# <td>{{ expenseTransaction.id }}</td> #}
                            <td>{{ expenseTransaction.paymentDate | date('m-d') }}</td>
                            {# <td>{{ expenseTransaction.user.userAccount.lastName }}</td> #}
                            <td>{{ expenseTransaction.expenseCategory.name }}</td>
                            {# <td>{{ expenseTransaction.expensePaymentCategory.name }}</td> #}
                            <td class="td-row-amount">{{ expenseTransaction.amount }}</td>
                            {# <td>{{ expenseTransaction.note }}</td> #}
                            <td class="td-row-operation">
                                <a href="{{ path('expense_transaction_edit', { id: expenseTransaction.id }) }}">編集</a>
                                <a onclick="return confirm('本当に削除しますか？');" href="{{ path('expense_transaction_delete', { id: expenseTransaction.id }) }}">削除</a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </main>

    {% include 'mobile/_base_layout/base_footer.html.twig' with {'footerLinks': footerLinks} %}

{% endblock %}